### ISSUE TITLE
File converted to temporary

### ISSUE THREAD

**Issue by moovida** [shannah/cn1-filechooser#1]
Hi, I like this extension, becaus eon dektop and android builds it make very much sense to use the filesystem.

When I use it in the simulator, the problem is that the selected file seems to be copied over into a tmp folder, like for example:

```
[EDT] 0:0:37,614 - Selected file: file:///tmp/temp6745774089518591051..gpap
```
Why is this done? It doesn't make much sense to me.

**Comment by codenameone** [comment]
The logic behind this is to provide an experience similar to the one you'd get on the devices and consistency among devices.

When acquiring an image some devices won't give you a direct link to the file as the original file resides in the gallery/camera app or some other place like that. So instead the API lets you copy the content locally. To make the behavior consistent we always copy locally so you can do things like modify the original file and it would work for all cases.

**Comment by moovida** [comment]
This limits the case in which the user needs to modify the file, as for example a database. He will always just modify the copy. That is a pity, because the filechooser is a really useful tool.

**Comment by codenameone** [comment]
Yes. That might be something we can provide as a configuration option but the logic should still default to this portable behavior. If you rely on this behavior you'd have hard to track issues on the device.

**Comment by moovida** [comment]
A configuration option to make this possible on devices that support this would be amazing.

**Comment by shannah** [comment]
I have added a method `FileChooser.setOpenFilesInPlace(true);` which will allow you to change this behaviour in the simulator.  Right now this flag doesn't affect any devices, but by the look of it, Android may already return the "real" path in some cases (like external storage)-- and in the other cases, it may not be possible to change the behaviour anyways.

This depends on a change in the Codename One core project which will be available in the next update on Friday.

**Comment by moovida** [comment]
What do you mean with the comment about Android? Because I had tested it on android and the file I targeted always got copied over from the sdcard to the internal application folder. I think that is what happens here? https://github.com/codenameone/CodenameOne/blob/master/Ports/Android/src/com/codename1/impl/android/AndroidImplementation.java#L6284-L6295
